### ISSUE TITLE
Columns - Add columns for: Created By, Created Date, Last Modified by , Last modified by date

### ISSUE THREAD

**Issue by EDUT-Equinor** [equinor/lighthouse-client#1528]
## Expected outcome

 
We should add columns for Created By & last Modified by where possible, so we can easily see who to contact, for example if a tag has been added. These columns can come at the end of columns
![image](https://github.com/equinor/lighthouse-client/assets/147052136/2b19792a-099b-4bfc-9ae7-8e61c01b9379)

This should be on all WOs / any data input, including pictures and documents

## Acceptance Criteria

 - [ ] last modified by
- [ ] last modified date
- [ ] Created by
- [ ] Created by date

## Tasks

- [ ] expand existing [view_name] with [fields]
- [ ] fetch and display [fields] in [Application|SideSheetTab]

**Comment by JoneUE** [comment]
@EDUT-Equinor Are you thinking when the RC was last updated or created? Or the tags itself? Cause we don't have data for created by or udated by in FAM. Only the dates

**Comment by EDUT-Equinor** [comment]
when it was last updated

**Comment by MagnusGjosund** [comment]
Is this still relevant? Doesn't seem like @EDUT-Equinor answered on @JoneUE question.

**Comment by EDUT-Equinor** [comment]
i know it would really help to keep track of what has been done and by who when the ship is offshore. when people go on rotation and add a valve tag for example, but forget to add any text about the valve they added, it will confuse the next person on rotation, so its good to have a record of who has added what, and at what time.

regarding jones question, my apologies, what i should have said was:

- We want the date a valve was Added & Last modified to the RC, and who this was done by. We do not the date the tag was created in PCS / last modified in PCS.

Apparently on JS it has been very useful to know who has added a tag / updated this and that from an RC. When people are on a 2;4 rotation, its really easy to lose track of what has been done. with RC, we plan to have more users than just the RC coordinators making RCs, so even more important to have oversight on who has created what / who has modified something.

An RC may be made by one person, and edited by several others

- 

-
